id: PBEEDCDB2
initial_creation_type: ocr
source_metadata:
  volumes:
    de77fba8a65d4fa6aed737607e8d5935:
      base_file: v070.txt
      image_group_id: I1PD95915
      title: ཐེག་པ་ཆེན་པོ་རྒྱུད་བླ་མའི་བསྟན་བཅོས་རྣམ་པར་བཤད་པ།
      total_pages: 1505
      volume_number: 70
